import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

def fgsm_attack(input_batch_data: torch.tensor, model: torch.nn.Module, input_shape: tuple, epsilon: float) -> torch.Tensor:
    """
    Apply the FGSM attack to input images given a pre-trained PyTorch model.

    Args:
        input_batch_data (ndarray): Batch of input images as a 4D numpy array.
        model (nn.Module): Pre-trained PyTorch model to be attacked.
        input_shape (tuple): Shape of the input array.
        epsilon (float): Magnitude of the perturbation for the attack.

    Returns:
        adversarial_batch_data (ndarray): Adversarial images generated by the FGSM attack.
    """
    # Set the model to evaluation mode
    model.eval()

    # Check if GPU is available
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Move the model and input batch data to the appropriate device
    model.to(device)
    input_batch_data = torch.tensor(input_batch_data).to(device)

    # Disable gradient computation for all model parameters
    for param in model.parameters():
        param.requires_grad = False

    adversarial_batch_data = []
    for img in input_batch_data:
        # Convert the input image to a PyTorch tensor with dtype=torch.float32 and enable gradient computation
        img = img.clone().detach().to(torch.float32).requires_grad_(True)

        # Move the input image tensor to the same device as the model
        img = img.to(device)

        # Make a forward pass through the model and get the predicted class scores for the input image
        preds = model(img.reshape(input_shape))

        # Compute the loss by selecting the class with the highest predicted score
        target = torch.argmax(preds)
        loss = torch.nn.functional.cross_entropy(preds, target.unsqueeze(0))

        # Compute gradients of the loss with respect to the input image pixels
        model.zero_grad()
        loss.backward()

        # Calculate the sign of the gradients
        gradient_sign = img.grad.sign()

        # Create the adversarial example by adding the signed gradients to the original image
        adversarial_img = img + epsilon * gradient_sign

        # Clip the adversarial image to ensure pixel values are within the valid range
        adversarial_img = torch.clamp(adversarial_img, 0, 1)

        adversarial_batch_data.append(adversarial_img.cpu().detach().numpy())

    return adversarial_batch_data



def gradient_map(input_batch_data: torch.tensor, model: torch.nn.Module, input_shape: tuple, backprop_type: str = 'guided') -> torch.Tensor:
    """
    Generate a gradient map for a batch of input images given a pre-trained PyTorch model.

    Args:
        input_batch_data (ndarray): Batch of input images as a 4D numpy array.
        model (nn.Module): Pre-trained PyTorch model used to generate the gradient map.
        input_shape (tuple): Shape of the input array.
        backprop_type (str, optional): Type of backpropagation. Supported values: 'guided', 'relu'.
            Defaults to 'guided'.

    Returns:
        gradient_maps (ndarray): Gradient map for the input images.
    """
    # Switch to training mode only if the model contains RNN layers
    has_rnn_layers = any(isinstance(layer, torch.nn.RNNBase) for layer in model.children())
    if has_rnn_layers:
        model = model.train()
    else:
        model.eval()

    # Check if GPU is available
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Move the model to the appropriate device
    model.to(device)

    # Convert the input batch to PyTorch tensor with dtype=torch.float32
    input_batch_data = torch.tensor(input_batch_data, device=device, dtype=torch.float32, requires_grad=True)

    # Make a forward pass through the model and get the predicted class scores for the input images
    preds = model(input_batch_data.view(-1, *input_shape))

    # Compute the scores and indices of the class with the highest predicted scores
    scores, _ = torch.max(preds, 1)

    # Zero out any existing gradients
    model.zero_grad()

    # Ensure that the score tensor requires gradients
    scores = scores.requires_grad_()

    # Compute gradients of the scores with respect to the input images
    grad_scores = torch.autograd.grad(outputs=scores, inputs=input_batch_data, grad_outputs=torch.ones_like(scores), create_graph=True)[0]

    # Switch back to evaluation mode if necessary
    if has_rnn_layers:
       model = model.eval()

    if backprop_type == 'guided':
        # Apply guided backpropagation
        gradients = grad_scores * (grad_scores > 0).float()  # ReLU-like operation
        gradient_maps = gradients.norm(dim=1)
    elif backprop_type == 'relu':
        # Apply ReLU backpropagation
        gradients = (grad_scores > 0).float()  # ReLU operation
        gradient_maps = gradients.norm(dim=1)
    else:
        # Default to vanilla backpropagation
        gradient_maps = grad_scores.norm(dim=1)

    return gradient_maps.cpu().detach().numpy()



def gradient_ascent(input_batch_data: torch.tensor, model: torch.nn.Module, input_shape: tuple, target_neuron: int, num_iterations: int = 100, step_size: float = 1.0) -> torch.Tensor:
    """
    Perform gradient ascent to generate an image that maximizes the activation of a target neuron given a pre-trained PyTorch model.

    Args:
        input_batch_data (ndarray): Batch of input images as a 4D numpy array.
        model (nn.Module): Pre-trained PyTorch model used for gradient ascent.
        input_shape (tuple): Shape of the input array.
        target_neuron (int): Index of the target neuron to maximize activation.
        num_iterations (int, optional): Number of gradient ascent iterations. Defaults to 100.
        step_size (float, optional): Step size for each iteration. Defaults to 1.0.

    Returns:
        generated_images (ndarray): Generated images that maximize the activation of the target neuron.
    """
    # Set the model to evaluation mode
    model.eval()

    # Check if GPU is available
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Move the model to the appropriate device
    model.to(device)

    # Initialize the generated images
    generated_images = []
    for img in input_batch_data:
        # Convert the input image to a PyTorch tensor with dtype=torch.float32 and enable gradient computation
        img = img.clone().detach().to(torch.float32).requires_grad_(True)

        # Move the input image tensor to the same device as the model
        img = img.to(device)

        # Perform gradient ascent
        for _ in range(num_iterations):
            # Make a forward pass through the model and get the activation of the target neuron
            activation = model(img.reshape(input_shape))[:, target_neuron]

            # Reset gradients from previous iterations
            model.zero_grad()

            # Compute gradients of the target neuron activation with respect to the input image using torch.autograd.grad
            gradients = torch.autograd.grad(activation, img)[0]

            # Normalize the gradients
            gradients = F.normalize(gradients, dim=0)

            # Update the input image using the gradients and step size
            img.data += step_size * gradients

        # Append the generated image to the list
        generated_images.append(img.cpu().detach().numpy())

    return generated_images

