import torch
import numpy as np
import torch.nn.functional as F

def get_activation(input_data: torch.Tensor, model: torch.nn.Module, normalize: bool = True) -> np.ndarray:
    """
    Get the activation values for input data given a pre-trained PyTorch model.

    Args:
        input_data (torch.Tensor): Input data as a PyTorch tensor.
            Shape: (batch_size, channels, height, width)
        model (torch.nn.Module): Pre-trained PyTorch model used to generate the activation map.
        normalize (bool, optional): Flag to normalize the activation values. Default is True.

    Returns:
        activation (np.ndarray): Activation values for the input data based on the input model.
            Shape: (batch_size, channels, height, width)

    Notes:
        - This function directly returns the activation values obtained by forwarding the input data through the model.
        - The activation values represent the intermediate feature maps produced by the model after each layer's activation function.
        - The returned activation tensor has the same shape as the input_data tensor, preserving the batch size, channel count, height, and width.
        - If normalize is True, the activation values are normalized to the range [0, 1].
        - No additional processing, such as gradient computation, is applied to the activation values.
    """
    model.eval()  # Set the model to evaluation mode
    assert isinstance(input_data, torch.Tensor), "Input data must be a PyTorch tensor"
    assert input_data.device == next(model.parameters()).device, "Input data and model must be on the same device"

    with torch.no_grad():
        activation = model(input_data)  # Forward pass the input data through the model

    if normalize:
        activation = torch.nn.functional.normalize(activation, dim=1)

    return activation.detach().cpu().numpy()


def get_gradcam(input_data: torch.Tensor, model: torch.nn.Module, target_layer: torch.nn.Module) -> np.ndarray:
    """
    Generate Grad-CAM (Gradient-weighted Class Activation Mapping) for input data given a pre-trained PyTorch model.

    Args:
        input_data (torch.Tensor): Input data as a PyTorch tensor. Shape: (batch_size, channels, height, width)
        model (torch.nn.Module): Pre-trained PyTorch model used to generate the Grad-CAM.
        target_layer (torch.nn.Module): Target layer of the model from which the gradients are obtained.

    Returns:
        np.ndarray: Grad-CAM heatmap for the input data.
    """
    model.eval()
    assert isinstance(input_data, torch.Tensor), "Input data must be a PyTorch tensor"
    assert input_data.device == next(model.parameters()).device, "Input data and model must be on the same device"

    # Forward pass
    output = model(input_data)
    _, predicted_class = torch.max(output, dim=1)
    predicted_class = predicted_class.squeeze()

    # Backward pass
    model.zero_grad()
    output[:, predicted_class].backward(retain_graph=True)

    # Get the gradients of the target layer
    gradients = target_layer.weight.grad
    alpha = torch.mean(gradients, dim=[2, 3], keepdim=True)
    activations = target_layer(input_data)

    # Weighted sum of activations
    weighted_sum = torch.sum(alpha * activations, dim=1, keepdim=True)
    weighted_sum = F.relu(weighted_sum)

    # Upsample the weighted sum to the input size
    upsampled = F.interpolate(weighted_sum, size=(input_data.size(2), input_data.size(3)), mode='bilinear', align_corners=False)
    upsampled = upsampled.squeeze()

    # Normalize the Grad-CAM heatmap
    normalized_heatmap = upsampled.detach().cpu().numpy()
    normalized_heatmap = (normalized_heatmap - np.min(normalized_heatmap)) / (np.max(normalized_heatmap) - np.min(normalized_heatmap))

    return normalized_heatmap


def get_saliency(input_data: torch.Tensor, model: torch.nn.Module, normalize: bool = True) -> np.ndarray:
    """
    Generate the saliency map for input data given a pre-trained PyTorch model.

    Args:
        input_data (torch.Tensor): Input data as a PyTorch tensor.
            Shape: (batch_size, channels, height, width)
        model (torch.nn.Module): Pre-trained PyTorch model used to generate the saliency map.
        normalize (bool, optional): Flag to normalize the saliency map. Default is True.

    Returns:
        saliency_map (np.ndarray): Saliency map for the input data based on the input model.
            Shape: (batch_size, height, width)

    Notes:
        - This function computes the saliency map, which represents the importance of each input pixel on the model's output.
        - The saliency map is generated by computing the absolute gradients of the model's output with respect to the input data.
        - The returned saliency map highlights the regions in the input that have the most significant influence on the model's predictions.
        - The saliency map is a visualization tool for understanding the model's decision-making process.
        - If normalize is True, the saliency map values are normalized to the range [0, 1].
        - Higher saliency values indicate pixels that have a stronger influence on the model's output.
    """
    model.eval()  # Set the model to evaluation mode
    assert isinstance(input_data, torch.Tensor), "Input data must be a PyTorch tensor"
    assert input_data.device == next(model.parameters()).device, "Input data and model must be on the same device"

    with torch.enable_grad():
        input_data.requires_grad_(True)  # Enable gradient computation for the input data

        output = model(input_data)  # Forward pass the input data through the model
        gradients = torch.autograd.grad(outputs=output, inputs=input_data, grad_outputs=torch.ones_like(output), create_graph=True)[0]

    saliency_map = gradients.abs().detach().cpu().numpy()  # Compute the absolute gradients and convert to a numpy array

    if normalize:
        min_vals = np.min(saliency_map, axis=(1, 2), keepdims=True)
        max_vals = np.max(saliency_map, axis=(1, 2), keepdims=True)
        saliency_map = (saliency_map - min_vals) / (max_vals - min_vals + 1e-8)

    return saliency_map


def get_gradient(input_data: torch.Tensor, model: torch.nn.Module) -> np.ndarray:
    """
    Get the gradients of the model's output with respect to the input data.

    Args:
        input_data (torch.Tensor): Input data as a PyTorch tensor.
            Shape: (batch_size, channels, height, width)
        model (torch.nn.Module): Pre-trained PyTorch model used to generate the gradients.

    Returns:
        gradients (np.ndarray): Gradients of the model's output with respect to the input data.
            Shape: (batch_size, channels, height, width)

    Notes:
        - This function computes the gradients of the model's output with respect to the input data.
        - The gradients capture how small changes in the input affect the model's output.
        - The returned gradients tensor has the same shape as the input_data tensor, preserving the batch size, channel count, height, and width.
    """
    model.eval()  # Set the model to evaluation mode
    assert isinstance(input_data, torch.Tensor), "Input data must be a PyTorch tensor"
    assert input_data.device == next(model.parameters()).device, "Input data and model must be on the same device"

    with torch.enable_grad():
        input_data.requires_grad_(True)  # Enable gradient computation for the input data

        output = model(input_data)  # Forward pass the input data through the model
        gradients = torch.autograd.grad(outputs=output, inputs=input_data, grad_outputs=torch.ones_like(output), create_graph=True)[0]

    return gradients.detach().cpu().numpy()
