# Workflow for building and deploying Sphinx documentation to GitHub Pages
name: Build and Deploy Sphinx Docs

on:
  # Runs on pushes to any branch
  push:
    branches: "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation with Sphinx
        working-directory: ./docs
        run: |
          make clean
          make html

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            deploy_key: ${{ secrets.DEPLOY_KEY }}
            publish_dir: ./docs/build/html
