name: Python Testing

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8  # Set Python version to 3.8 or 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Change to a version compatible with TensorFlow
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python setup.py install
        conda install pytest
        pytest
